
func InstallRouter(db gorm.DB, router *gin.Engine) {
  InstallActivityRouter(db, router)
  InstallCommentRouter(db, router)
  InstallContentRouter(db, router)
  InstallFileRouter(db, router)
  InstallGroupRouter(db, router)
  InstallGroupAdminRouter(db, router)
  InstallLikeRouter(db, router)
  InstallLoggingRouter(db, router)
  InstallMigrationRouter(db, router)
  InstallModuleEnabledRouter(db, router)
  InstallNotificationRouter(db, router)
  InstallPostRouter(db, router)
  InstallProfileRouter(db, router)
  InstallProfileFieldRouter(db, router)
  InstallProfileFieldCategoryRouter(db, router)
  InstallSettingRouter(db, router)
  InstallSpaceRouter(db, router)
  InstallSpaceMembershipRouter(db, router)
  InstallSpaceModuleRouter(db, router)
  InstallSpaceSettingRouter(db, router)
  InstallUrlOembedRouter(db, router)
  InstallUserRouter(db, router)
  InstallUserFollowRouter(db, router)
  InstallUserHttpSessionRouter(db, router)
  InstallUserInviteRouter(db, router)
  InstallUserMentioningRouter(db, router)
  InstallUserModuleRouter(db, router)
  InstallUserPasswordRouter(db, router)
  InstallUserSettingRouter(db, router)
  InstallWallRouter(db, router)
  InstallWallEntryRouter(db, router)
}
